export const DEFAULT_DEPARTMENT_NAMES = [
  "Anestesiologia",
  "Cardiochirurgia",
  "Centro ustioni",
  "Chirurgia colorettale",
  "Chirurgia dei trapianti",
  "Chirurgia generale",
  "Chirurgia orale e maxillo-facciale",
  "Chirurgia ortopedica",
  "Chirurgia toracica",
  "Chirurgia traumatologica",
  "Chirurgia vascolare",
  "Ematologia",
  "Gastroenterologia",
  "Ginecologia",
  "Medicina d’urgenza",
  "Medicina interna",
  "Medicina ospedaliera",
  "Medico notturno",
  "Nefrologia",
  "Neonatologia",
  "Neurochirurgia",
  "Oncologia",
  "Oncologia ginecologica",
  "Ostetricia",
  "Medico del travaglio",
  "Perinatologia (gravidanze ad alto rischio)",
  "Otorinolaringoiatria — Chirurgia cervico-facciale",
  "Pneumologia",
  "Radiologia interventistica",
  "Terapia intensiva/Rianimazione",
  "Urologia",
];
